import { sql } from 'drizzle-orm'
import type { InferInsertModel, InferSelectModel } from 'drizzle-orm'
import { sqliteTable, text } from 'drizzle-orm/sqlite-core'

import { user } from './auth-schema'

// Better Auth tables — generated by `pnpm dlx auth@latest generate`
export * from './auth-schema'

export const tasks = sqliteTable('tasks', {
  id: text('id').primaryKey(),
  title: text('title').notNull(),
  status: text('status', { enum: ['todo', 'in_progress', 'done', 'canceled'] })
    .notNull()
    .default('todo'),
  userId: text('user_id')
    .notNull()
    .references(() => user.id, { onDelete: 'cascade' }),
  dueDate: text('due_date'),
  createdAt: text('created_at')
    .notNull()
    .default(sql`(current_timestamp)`),
  updatedAt: text('updated_at')
    .notNull()
    .default(sql`(current_timestamp)`),
})

export type Task = InferSelectModel<typeof tasks>
export type NewTask = InferInsertModel<typeof tasks>
