import { execSync } from 'node:child_process'
import fs from 'node:fs'
import path from 'node:path'

import type { ImageDimension, ImageEntry, OutputFormat } from './types'

interface GenerateOptions {
  entries: ImageEntry[]
  dimensions: Map<string, ImageDimension>
  outputFile: string
  outputFormat: OutputFormat
  requirePrefix?: string
  urlPrefix?: string
  imageSourceType?: string
  prettier?: boolean
}

/**
 * Generate TypeScript image source file(s) based on the output format.
 */
export const generateOutput = (options: GenerateOptions): void => {
  const { outputFormat } = options

  switch (outputFormat) {
    case 'require':
      generateRequireOutput(options)
      break
    case 'url':
      generateUrlOutput(options)
      break
  }
}

// ---------------------------------------------------------------------------
// Shared helpers
// ---------------------------------------------------------------------------

const buildNameType = (entries: ImageEntry[]): string =>
  entries.map((e) => `  | '${e.name}'`).join('\n')

const buildDimensionsRecord = (
  entries: ImageEntry[],
  dimensions: Map<string, ImageDimension>,
): string =>
  entries
    .map((e) => {
      const d = dimensions.get(e.name) ?? { width: 0, height: 0 }
      return `  '${e.name}': { width: ${d.width}, height: ${d.height} },`
    })
    .join('\n')

const buildRequireRecord = (entries: ImageEntry[], requirePrefix: string): string =>
  entries
    .map((e) => {
      const imgPath = e.type === 'svg' ? `converted-svg/${e.relativePath}` : e.relativePath
      return `  '${e.name}': require('${requirePrefix}/${imgPath}'),`
    })
    .join('\n')

const buildUrlRecord = (entries: ImageEntry[], urlPrefix: string): string =>
  entries
    .map((e) => {
      const imgPath = e.type === 'svg' ? `converted-svg/${e.relativePath}` : e.relativePath
      return `  '${e.name}': '${urlPrefix}/${imgPath}',`
    })
    .join('\n')

const header = `/* eslint-disable */
// This file is auto-generated by @chalkboard/image-indexer
// Do not edit this file directly\n`

const writeAndFormat = (filePath: string, content: string, prettier: boolean): void => {
  const dir = path.dirname(filePath)
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true })
  }
  fs.writeFileSync(filePath, content, 'utf8')

  if (prettier) {
    try {
      execSync(`npx prettier --write "${filePath}"`, { stdio: 'pipe' })
    } catch {
      console.warn(`Failed to format ${filePath} with Prettier`)
    }
  }
}

// ---------------------------------------------------------------------------
// Output format: require (single .ts with require() calls)
// ---------------------------------------------------------------------------

const generateRequireOutput = (options: GenerateOptions): void => {
  const {
    entries,
    dimensions,
    outputFile,
    requirePrefix = '.',
    imageSourceType,
    prettier = true,
  } = options
  const filePath = `${outputFile}.ts`

  const sourceTypeImport = imageSourceType ? `${imageSourceType}\n\n` : ''
  const sourceValueType = imageSourceType ? extractTypeName(imageSourceType) : 'unknown'

  const content = `${header}
${sourceTypeImport}export type ImageName =
${buildNameType(entries)}

export const imageSources: Record<ImageName, ${sourceValueType}> = {
${buildRequireRecord(entries, requirePrefix)}
} as const

export const nativeDimensions: Record<ImageName, { width: number; height: number }> = {
${buildDimensionsRecord(entries, dimensions)}
} as const
`

  writeAndFormat(filePath, content, prettier)
  console.log(`Generated require output: ${filePath}`)
}

// ---------------------------------------------------------------------------
// Output format: url (single .ts with URL strings)
// ---------------------------------------------------------------------------

const generateUrlOutput = (options: GenerateOptions): void => {
  const { entries, dimensions, outputFile, urlPrefix = '', prettier = true } = options
  const filePath = `${outputFile}.ts`

  const content = `${header}
export type ImageName =
${buildNameType(entries)}

export const imageSources: Record<ImageName, string> = {
${buildUrlRecord(entries, urlPrefix)}
} as const

export const nativeDimensions: Record<ImageName, { width: number; height: number }> = {
${buildDimensionsRecord(entries, dimensions)}
} as const
`

  writeAndFormat(filePath, content, prettier)
  console.log(`Generated URL output: ${filePath}`)
}

// ---------------------------------------------------------------------------
// Utility
// ---------------------------------------------------------------------------

/** Extract the type name from an import statement like `import type { Foo } from 'bar'` → `Foo` */
const extractTypeName = (importStatement: string): string => {
  const match = importStatement.match(/\{\s*(\w+)\s*\}/)
  return match?.[1] ?? 'unknown'
}
